---
title: "Adding Analyses to a Plan"
author: "Richard Aubrey White"
date: "2022-06-02"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Adding Analyses to a Plan}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

## Definitions

+--------------+---------------------------------------------------------------+
| Object       | Description                                                   |
+==============+===============================================================+
| argset       | A named list containing a set of arguments.                   |
+--------------+---------------------------------------------------------------+
| analysis     | These are the fundamental units that are scheduled in `plnr`: |
|              |                                                               |
|              | -   1 argset                                                  |
|              | -   1 function that takes two arguments:                      |
|              |     1.  data (named list)                                     |
|              |                                                               |
|              |     2.  argset (named list)                                   |
+--------------+---------------------------------------------------------------+
| plan         | This is the overarching "scheduler":                          |
|              |                                                               |
|              | -   1 data pull                                               |
|              | -   1 list of analyses                                        |
+--------------+---------------------------------------------------------------+

: Table 1. A list of the broad technical terms used in `plnr`

+----------------------+--------------------------------------------------------------+
| Plan Type            | Description                                                  |
+======================+==============================================================+
| Single-function plan | Same function applied multiple times with different argsets. |
+----------------------+--------------------------------------------------------------+
| Multi-function plan  | Different functions applied to the same datasets.            |
+----------------------+--------------------------------------------------------------+

: Table 2. The different types of plans.

+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Plan Type            | Example                                                                                                                                                             |
+======================+=====================================================================================================================================================================+
| Single-function plan | Multiple strata (e.g. locations, age groups) that you need to apply the same function to to (e.g. outbreak detection, trend detection, graphing).                   |
+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Single-function plan | Multiple variables (e.g. multiple outcomes, multiple exposures) that you need to apply the same statistical methods to (e.g. regression models, correlation plots). |
+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Multi-function plan  |                                                                                                                                                                     |
+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Table 3. Examples of the different types of plans.

## Single-function plan

This approach is generally used when you:

-   Have multiple strata (e.g. locations, age groups) that you need to apply the same statistical methods to.
-   Have multiple variables (e.g. multiple exposures, multiple outcomes) that you want to apply the same statistical methods to.

When we apply the same function multiple times, it is preferable to add the argsets first, and then apply the analysis function just before running the analyses.

### Analysis within multiple strata

```{r, collapse=FALSE}
library(ggplot2)
library(data.table)
library(magrittr)

# We begin by defining a new plan
p <- plnr::Plan$new()

# Data function
data_fn <- function(){
  return(plnr::norway_covid19_cases_by_time_location)
}

# We add sources of data
# We can add data directly
p$add_data(
  name = "covid19_cases",
  fn_name = "data_fn"
)

p$get_data()

location_codes <- p$get_data()$covid19_cases$location_code %>%
  unique() %>% 
  print()

p$add_argset_from_list(
  plnr::expand_list(
    location_code = location_codes,
    granularity_time = "isoweek"
  )
)
p$get_argsets_as_dt()

# We can then add a simple analysis that returns a figure:

# To do this, we first need to create an analysis function
# (takes two arguments -- data and argset)
analysis_fn <- function(data, argset){
  if(plnr::is_run_directly()){
    data <- p$get_data()
    argset <- p$get_argset(1)
  }
  pd <- data$covid19_cases[
    location_code == argset$location_code &
    granularity_time == argset$granularity_time
  ]
  
  q <- ggplot(pd, aes(x=isoyearweek, y=covid19_cases_testdate_n, group = 1))
  q <- q + geom_line()
  q <- q + labs(title = argset$location_code)
  q
}

p$apply_analysis_fn_to_all(fn_name = "analysis_fn")

p$run_one(1)
q <- p$run_all()
q[[1]]
q[[2]]
```

## Applying different functions to the same dataset.
